# Generated by Django 5.1.5 on 2025-01-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mobiles/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='ShopSmart.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('storage', models.CharField(max_length=50)),
                ('battery', models.IntegerField()),
                ('screen_size', models.FloatField()),
                ('camera', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=50)),
                ('mobile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='ShopSmart.mobile')),
            ],
        ),
    ]
